feat: Port Translation
dentproject/docs.dent.dev pull request #43
Opened 2024-05-17 11:37 UTC by royalpinto007

Documentation for Port Translation.

2024-05-22 23:01 UTC, taskin0003 approved these changes

2024-05-23 20:47 UTC, taskin0003 requested changes

2024-05-23 20:47 UTC, taskin0003 commented on NetworkConfigurations/NetworkAddressingAndFilteringSubCategories/PortTranslation.md
> +iptables -t nat -L -n -v
please add the output here.

2024-05-23 20:47 UTC, taskin0003 commented on NetworkConfigurations/NetworkAddressingAndFilteringSubCategories/PortTranslation.md
> +# Port Translation
Please add a graph of sample topology (you can use VMs) and show the config works (i.e. add a simple command like ping and show it is successful.)

2024-05-23 20:47 UTC, taskin0003 commented on NetworkConfigurations/NetworkAddressingAndFilteringSubCategories/PortTranslation.md
> +
Yes, you've typed these descriptions but I think it works better if you had a graph of sample topology and show the config works (i.e. add a simple command like ping and show it is successful.)

2024-06-05 06:00 UTC, taskin0003 approved these changes

2024-06-09 08:00 UTC, taraschornyiplv approved these changes

2024-06-12 13:47 UTC, merged